version: '3.9'
services:
  end-app:
    build:
      context: .
    container_name: end-app
    depends_on:
      - postgres-db
    environment:
      spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
      spring.datasource.username=postgres
      spring.datasource.password=Haikus51w
      spring.jpa.hibernate.ddl-auto=update
      spring.jpa.show-sql=true
      spring.flyway.enabled=true
    ports:
      - "8081:8080"
    command:
      - java -jar build/libs/end-0.0.1-SNAPSHOT.jar

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      postgres_username: postgres
      postgres_password: postgres
      postgres_db: postgres
    ports:
      - "5432:5432"